### ISSUE TITLE
Submit extension to packagist.org

### ISSUE THREAD

**Issue by Tjitse-E** [buckaroo-it/Magento2_Hyva_Checkout#11]
And update the installation instructions: https://github.com/buckaroo-it/Magento2_Hyva_Checkout#installation

**Comment by Buckaroo-Rene** [comment]
Hi @Tjitse-E ,

Thank you for reaching out to us.
We've submitted the extenstion to packagist and updated the readme regarding the installation instructions.
Please let us know if you still encounter any issues.
https://packagist.org/packages/buckaroo/magento2-hyva-checkout
