### ISSUE TITLE
BP-3545 PHP 8.2 in composer.json

### ISSUE THREAD

**Issue by Shiriaev** [buckaroo-it/Magento2_Hyva_Checkout#21]
Hello!

Current  Magento 2 version supports PHP 8.2. However, in module composer.json still PHP 8.1, and this is the reason of many inconvenient things with CI/CD.

I tried install with `--ignore-patform-reqs` and looks like everything working fine.

Please consider to update PHP version. Thanks!

Best regards,
Pavel

**Comment by Shiriaev** [comment]
I created PR with this update: https://github.com/buckaroo-it/Magento2_Hyva_Checkout/pull/23

**Comment by Buckaroo-Rene** [comment]
Hi @Shiriaev,

Thank you for logging this issue, we'll take a look at your PR.

Best regards,
René

**Comment by Buckaroo-Rene** [comment]
Closing this issue since it was already released in version [1.1.2](https://github.com/buckaroo-it/Magento2_Hyva_Checkout/releases/tag/1.1.2).
Thanks again for the PR @Shiriaev!
