### ISSUE TITLE
BP-3546 Use object as array in \Buckaroo\HyvaCheckout\Block\Totals\Fee::getTotal

### ISSUE THREAD

**Issue by Shiriaev** [buckaroo-it/Magento2_Hyva_Checkout#22]
Hello Everyone!

I found error right after installation `Hyva_Checkout` and this module. 

The problem in Use object as array in `\Buckaroo\HyvaCheckout\Block\Totals\Fee::getTotal`:

`isset($totalData['extension_attributes']['buckaroo_fee'])` assumed that extension attributes is an array, but in our case extension attributes is an object. From my point of view, this function should be something as follow:

```
    public function getTotal(): float
    {
        $totalData = $this->getSegment();
        $extensionAttributes = $totalData['extension_attributes'] ?? null;
        if (
            $extensionAttributes &&
            is_scalar($extensionAttributes->getBuckarooFee())
        ) {
            return floatval($extensionAttributes->getBuckarooFee());
        }
        return 0;
    }
```
Please consider to add such fixes to the module. Thanks!

**Comment by Buckaroo-Rene** [comment]
Hi @Shiriaev,

Thanks for mentioning this issue. We'll take a look at it.

Best regards,
René

**Comment by Buckaroo-Rene** [comment]
@Shiriaev ,

Do you perhaps also have the Magento 2 version and PHP version that you are using?
Thanks alot.

Best regards,
René

**Comment by Shiriaev** [comment]
Hello @Buckaroo-Rene !

Magento 2.4.6-p3
PHP 8.2.18

**Comment by Tjitse-E** [comment]
@Buckaroo-Rene  I can confirm this:
```
Error: Cannot use object of type Magento\Quote\Api\Data\TotalSegmentExtension as array in vendor/buckaroo/magento2-hyva-checkout/Block/Totals/Fee.php:54
```

Versions:
buckaroo/magento2-hyva-checkout - 1.1.2
hyva-themes/magento2-hyva-checkout - 1.1.17

Crashes out of the box.

**Comment by larsmbm** [comment]
We can confirm that we have the same issue. Is there any indication of when this will be resolved?

**Comment by larsmbm** [comment]
Could you please provide an update on this ticket? We're experiencing the same problem and would be grateful for any news.
