### ISSUE TITLE
BP-3715 Remove LoggerInterface from MethodMetaData.php

### ISSUE THREAD

**Issue by sanderjongsma** [buckaroo-it/Magento2_Hyva_Checkout#30]
The `LoggerInterface` isn't used in this file: `\Hyva\Checkout\Model\MethodMetaData` in the newest version of the checkout. So the extended version of your `Model/MethodMetaData.php` should also be updated. I don't want to make a MR because it would not be backwords compatible with other versions of the hyva checkout. But I think the extend of `Model/MethodMetaData.php` in your module should be removed and since the `renderIcon` is public, maybe with a plugin the same result can be achieved and by that it should also be more compatible with future updates in the hyva checkout

**Comment by Buckaroo-Rene** [comment]
Hi @sanderjongsma ,

Thanks for informing us about this issue.
We've created a fix while for this while we where working to support the latest version of Hyvä Checkout (https://github.com/buckaroo-it/Magento2_Hyva_Checkout/pull/34).
This will be included in our next release.

**Comment by Buckaroo-Rene** [comment]
@sanderjongsma ,
The fix is now included in version [1.2.0](https://github.com/buckaroo-it/Magento2_Hyva_Checkout/releases/tag/v1.2.0) of our Hyvä Checkout module.
Please make sure to also update the main Buckaroo Plugin for Magento 2 to ensure full compatibility.
