### ISSUE TITLE
BP-3191 Module loads too fast (Unexpected identifier)

### ISSUE THREAD

**Issue by HyperC** [buckaroo-it/Magento2_Hyva_Checkout#8]
For some reason this module throws errors on our staging environment (production mode), during load:

![image](https://github.com/buckaroo-it/Magento2_Hyva_Checkout/assets/5372580/cf53ac6b-45a5-4b1c-8e9b-60cb99d3ab1f)

Locally it does work fine. For some reason it doesn't have a window object in the after.phtml on line:

```window.addEventListener('buckaroo-modal-show', (event) => {```

**Comment by harli91** [comment]
Hello @HyperC what version of the plugin are you using, also what version of hyva checkout? I am unable to reproduce this in our environment

**Comment by HyperC** [comment]
Hi @harli91 , I'm using the 1.0.0 version on this module (the only release) and the latest version of hyva checkout (1.1.8). The buckaroo/magento2 version I'm using is 1.46.1.
I noticed on my local environment that if I switch to production mode, I also get the error. Have you also tried that?

**Comment by Buckaroo-Rene** [comment]
@HyperC ,
Thank you for your quick reply with the versions.
We'll research this straight away and let you know when we found the cause and a solution for it.

**Comment by harli91** [comment]
Hi @HyperC I've moved some thing around, created branch https://github.com/buckaroo-it/Magento2_Hyva_Checkout/tree/move-js, swich to this branch and check if the errors still exists, thanks

**Comment by HyperC** [comment]
@harli91 Thanks! Your fix seems to do the trick. Will push it to our staging env now, but locally all works fine! :)

**Comment by Buckaroo-Rene** [comment]
@HyperC ,
Thank you for the confirmation for now.
Please let us know if you encounter any other issues.

**Comment by Buckaroo-Rene** [comment]
@HyperC ,
We are currently testing our changes as well and we will be doing a new release when that is all done.
Hopefully this will be this week and otherwise next week.
